# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=36)),
                ('genre', models.CharField(blank=True, default='default_user', max_length=24)),
                ('tag', models.CharField(blank=True, default='', max_length=24)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('username', models.CharField(blank=True, default='default_user', max_length=24)),
                ('location', models.CharField(blank=True, default='', max_length=24)),
                ('favorite_musician', models.CharField(blank=True, default='', max_length=36)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
    ]
