# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConcertifyApi', '0002_auto_20170424_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='longtitude',
            field=models.FloatField(default=0),
        ),
    ]
