# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConcertifyApi', '0003_auto_20170424_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=24)),
                ('musician', models.CharField(blank=True, default='', max_length=24)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MainHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=36)),
                ('address', models.CharField(blank=True, default='', max_length=24)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagID', models.IntegerField(default=0)),
                ('text', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ('tagID',),
            },
        ),
    ]
