# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConcertifyApi', '0004_concert_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=36)),
                ('address', models.CharField(blank=True, default='', max_length=24)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
